/*
 * This source file was generated by the Gradle 'init' task
 */
package proyecto1;
import java.util.Stack;

public class App {

    public static void main(String[] args) {
        Stack<Products> inventario = new Stack<Products>();
        Servicios s = new Servicios();

        System.out.println("Sistema de inventario\n");
        
        System.out.println("Agregar productos\n");
        System.out.println(
                "____________________________________________________________________________________________________________\n");
        s.agregarProducto(inventario, 1, "Leche Lala", "Lacteos", 10, 20);
        s.agregarProducto(inventario, 2, "Coca Cola", "Refrescos", 20, 15);
        s.agregarProducto(inventario, 1, "Leche Santa Clara", "Lacteos", 10, 30);
        s.mostrarHistorial();
        System.out.println(
                "____________________________________________________________________________________________________________\n");

        System.out.println("Modificar productos\n");
        System.out.println(
                "____________________________________________________________________________________________________________\n");
        s.modificarCantidad(inventario, 1, 20);
        s.modificarPrecio(inventario, 2, 40);
        s.modificarCantidad(inventario, 3, 10);
        s.modificarPrecio(inventario, 3, 20);
        s.modificarCantidad(inventario, 2, 2);
        s.mostrarHistorial();
        System.out.println(
                "____________________________________________________________________________________________________________\n");

        System.out.println("Eliminar productos\n");
        System.out.println(
                "____________________________________________________________________________________________________________\n");
        s.mostrarProductos(inventario);
        s.eliminarProducto(inventario, 1);
        s.eliminarProducto(inventario, 3);
        s.mostrarProductos(inventario);
        System.out.println(
                "____________________________________________________________________________________________________________\n");
    }
}
